### ISSUE TITLE
Gala.sh and GALACTICA_HOME's variable

### ISSUE THREAD

**Issue by nico2511** [Galactica-corp/networks#26]
Hello, in gala.sh 'GALACTICA_HOME' is defined in raw mode but in create-home you specify that you can use a custom path, but anyway the variable in gala.sh is used first?

> create-home.sh: Initializes the node's home directory with necessary configuration files. You can specify a custom home directory with the GALACTICA_HOME environment variable. This environment variable uses in all scripts.

`export GALACTICA_HOME=~/.galactica # = useless ?`

**Comment by yakud** [comment]
Thanks for creating the issue. 
Indeed, I found a bug in setting the environment variable. Should be fixed in the main branch. Could you check it please?

**Comment by nico2511** [comment]
Hello.
Can't test, but "moniker" should have a default value no ? Especially for noob and AIO installation ?

**Comment by nico2511** [comment]
You could generate a random value and create a random MONIKER like NODE-493828*
