### ISSUE TITLE
sed command in create-home seems wrong

### ISSUE THREAD

**Issue by Pretid** [Galactica-corp/networks#3]
Hi, when running create-home.sh we face this issue at then end on the sed command : 

sed: can't read s/moniker = "validator"/moniker = "testnet_keys"/g: No such file or directory

I think that the issue is the double '' after -i but I'm not a sed expert ;-) 
sed -i **''** 's/moniker = "validator"/moniker = "'$moniker'"/g'  "$GALACTICA_HOME/config/config.toml"

Hope it will help !

**Comment by yakud** [comment]
could you pull the latest changes and try again please?

**Comment by Pretid** [comment]
Works great thank you !
